variables: secrets.yml
schedules:
  - tasks: '*'
    interval:
      minutes: 10
templates:
  global:
    #make_rss:
      #file: /home/xbmc/public_html/flexget.rss
      #days: -1
      #items: 200
    #qbittorrent:
      #host: localhost
      #port: 9999
    #rtorrent:
      #uri: scgi://localhost:5001
    #transmission:
      #username: '{? transmission.usr ?}'
      #password: '{? transmission.pwd ?}'
      #port: 8093
    deluge:
      username: '{? deluge.username ?}'
      password: '{? deluge.password ?}'
    manipulate:
      - url:
          replace:
            regexp: '&amp'
            format: '&'
    metainfo_series: yes
    add_trackers: '{? trackers ?}'
  tvshows:
    thetvdb_lookup: yes
    template:
      - mailshow
    set:
      path: '/media/sda3/Video/Series/{{series_name}}/Season {{series_season}}'
  mailshow:
    notify:
      task:
        template: html.template
        via:
          - email:
              from: film-notify@asm0dey.ru
              to: '{? email.to ?}'
              smtp_host: smtp.yandex.ru
              smtp_port: 465
              smtp_ssl: true
              smtp_username: '{? email.usr ?}'
              smtp_password: '{? email.pwd ?}'
              smtp_tls: no
              html: yes
  mailpack:
    notify:
      task:
        template: html.template
        via:
          - email:
              from: film-notify@asm0dey.ru
              to: '{? email.to ?}'
              smtp_host: smtp.yandex.ru
              smtp_port: 465
              smtp_ssl: true
              smtp_username: '{? email.usr ?}'
              smtp_password: '{? email.pwd ?}'
              smtp_tls: no
              #html: yes
  mailmovie:
    notify:
      task:
        template: html.template
        via:
          - email:
              from: film-notify@asm0dey.ru
              to: '{? email.to ?}'
              smtp_host: smtp.yandex.ru
              smtp_port: 465
              smtp_ssl: true
              smtp_username: '{? email.usr ?}'
              smtp_password: '{? email.pwd ?}'
              smtp_tls: no
              #html: yes
tasks:
  Newstudio:
    template:
      - tvshows
    rss:
      url: '{? newstudio.address ?}'
    include: newstudio.yml
  lostfilm:
    rss:
      url: '{? lostfilm.url ?}'
    template:
      - tvshows
    include: litr-lost.yml
  litr-baibako:
    template:
      - tvshows
    rss: '{? baibako.url ?}'
    manipulate:
      - title:
          replace:
            regexp: 'e(\d{2}-)?(\d{2})'
            format: 'e\2'
      - title:
          replace:
            regexp: '/'
            format: ''
      - title:
          replace:
            regexp: '\[Новинка\]\s+'
            format: ''
      - title:
          replace:
            regexp: '\[Закрыта\]\s+'
            format: ''
    include: litr-baib.yml
    set:
      path: '/media/sda3/Video/Series/{{series_name}}'
  lutik:
    template:
      - tvshows
    rss: '{? lutik.address ?}'
    set:
      path: '/media/sda3/Video/Series/{{series_name}}'
    include: lutik.yml
    seen:
      fields: [title]
    manipulate:
      - title:
          replace:
            regexp: '. Серия (\d+)x(\d+)'
            format: ' (s\1e\2)'
  litr-rutr:
    template:
      - tvshows
    rss: '{? litr.address ?}'
    set:
      path: '/media/sda3/Video/Series/{{series_name}}'
    manipulate:
      - title:
          replace:
            regexp: 'Сезон: (\d+) / Серии: 1-(\d+) из \d+'
            format: 's\1e\2'
    series:
      - The Big Bang Theory:
          alternate_name: Теория Большого Взрыва
      - Call The Midwife:
          alternate_name: Вызовите акушерку
  rutr-films:
    csv:
      url: file:///home/xbmc/.flexget/films.csv
      values:
        title: 1
        url: 2
    set:
      path: '/media/sda3/Video/Films/{{ title }}'
    accept_all: yes

# vim: noai:ts=2:sw=2:et:
