web_server:
  bind: 0.0.0.0
  port: 3539
  run_v2: true
schedules:
  - tasks: '*'
    interval:
      minutes: 10
templates:
  global:
    notify:
      entries:
        what: accepted
        via:
          - telegram:
              bot_token: '***REMOVED***'
              parse_mode: markdown
              recipients:
                - group: asm0dey_series_download
    make_rss:
      file: /home/xbmc/public_html/flexget.rss
      days: -1
      items: 200
    #deluge: yes
    transmission:
      username: transmission
      password: transmission
    manipulate:
      - url:
          replace:
            regexp: '&amp'
            format: '&'
    metainfo_series: yes
    add_trackers:
      - http://0d.kebhana.mx:443/announce
      - http://explodie.org:6969/announce
      - http://mgtracker.org:6969/announce
      - http://node.611.to:9000/announce
      - http://omg.wtftrackr.pw:1337/announce
      - http://open.acgnxtracker.com:80/announce
      - http://open.acgtracker.com:1096/announce
      - http://open.trackerlist.xyz:80/announce
      - http://opentracker.xyz:80/announce
      - http://retracker.mgts.by:80/announce
      - http://retracker.telecom.by:80/announce
      - http://share.camoe.cn:8080/announce
      - http://t.nyaatracker.com:80/announce
      - http://therightsize.net:1337/announce
      - http://torrent.nwps.ws:80/announce
      - http://tracker.city9x.com:2710/announce
      - http://tracker.cypherpunks.ru:6969/announce
      - http://tracker.internetwarriors.net:1337/announce
      - http://tracker.port443.xyz:6969/announce
      - http://tracker.torrentyorg.pl:80/announce
      - http://tracker.tvunderground.org.ru:3218/announce
      - http://tracker.vanitycore.co:6969/announce
      - http://tracker1.itzmx.com:8080/announce
      - http://tracker2.itzmx.com:6961/announce
      - http://tracker3.itzmx.com:6961/announce
      - http://tracker4.itzmx.com:2710/announce
      - https://1337.abcvg.info:443/announce
      - https://2.track.ga:443/announce
      - https://evening-badlands-6215.herokuapp.com:443/announce
      - https://opentracker.xyz:443/announce
      - https://tracker.fastdownload.xyz:443/announce
      - udp://9.rarbg.to:2710/announce
      - udp://bt.xxx-tracker.com:2710/announce
      - udp://exodus.desync.com:6969/announce
      - udp://explodie.org:6969/announce
      - udp://ipv4.tracker.harry.lu:80/announce
      - udp://mgtracker.org:6969/announce
      - udp://open.demonii.si:1337/announce
      - udp://open.stealth.si:80/announce
      - udp://packages.crunchbangplusplus.org:6969/announce
      - udp://public.popcorn-tracker.org:6969/announce
      - udp://retracker.lanta-net.ru:2710/announce
      - udp://thetracker.org:80/announce
      - udp://tracker.coppersurfer.tk:6969/announce
      - udp://tracker.cypherpunks.ru:6969/announce
      - udp://tracker.ds.is:6969/announce
      - udp://tracker.iamhansen.xyz:2000/announce
      - udp://tracker.internetwarriors.net:1337/announce
      - udp://tracker.justseed.it:1337/announce
      - udp://tracker.kamigami.org:2710/announce
      - udp://tracker.opentrackr.org:1337/announce
      - udp://tracker.port443.xyz:6969/announce
      - udp://tracker.tiny-vps.com:6969/announce
      - udp://tracker.torrent.eu.org:451/announce
      - udp://tracker.toss.li:6969/announce
      - udp://tracker.tvunderground.org.ru:3218/announce
      - udp://tracker.uw0.xyz:6969/announce
      - udp://tracker.vanitycore.co:6969/announce
      - udp://tracker1.itzmx.com:8080/announce
      - udp://tracker2.itzmx.com:6961/announce
      - udp://tracker4.itzmx.com:2710/announce
      - udp://z.crazyhd.com:2710/announce
      - udp://zephir.monocul.us:6969/announce
  tvshows:
    thetvdb_lookup: yes
    template:
      - mailshow
    set:
      path: '/media/sda3/Video/Series/{{series_name}}/Season {{series_season}}'
  mailshow:
    notify:
      task:
        template: html.template
        via:
          - email:
              from: ***REMOVED***
              to:
                #- mail@example.com
                - ***REMOVED***
                - ***REMOVED***
              smtp_host: smtp.yandex.ru
              smtp_port: 465
              smtp_ssl: true
              smtp_username: "***REMOVED***"
              smtp_password: "***REMOVED***"
              smtp_tls: no
              html: yes
  mailpack:
    notify:
      task:
        template: html.template
        via:
          - email:
              from: ***REMOVED***
              to:
                #- mail@example.com
                - ***REMOVED***
                - ***REMOVED***
              smtp_host: smtp.yandex.ru
              smtp_port: 465
              smtp_ssl: true
              smtp_username: "***REMOVED***"
              smtp_password: "***REMOVED***"
              smtp_tls: no
              #html: yes
  mailmovie:
    notify:
      task:
        template: html.template
        via:
          - email:
              from: ***REMOVED***
              to:
                #- mail@example.com
                - ***REMOVED***
                - ***REMOVED***
              smtp_host: smtp.yandex.ru
              smtp_port: 465
              smtp_ssl: true
              smtp_username: "***REMOVED***"
              smtp_password: "***REMOVED***"
              smtp_tls: no
              #html: yes
tasks:
  #Baibako:
    #manipulate:
      #- title:
          #replace:
            #format: h264
            #regexp: x264
    #rss: http://baibako.tv/rss2.php?feed=dl&passkey=***REMOVED***&cat=507
    #rss: http://baibako.tv/rss2.php?feed=dl&passkey=***REMOVED***
    #template:
      #- tvshows
    #include: baibako.yml
  Lostfilm:
    verify_ssl_certificates: no
    #proxy: http://46.28.202.209 :8080
    template:
      - tvshows
    headers:
      cookie: uid=902055; pass=***REMOVED***; usess=***REMOVED***;
    rss: http://old.lostfilm.tv/rssdd.xml
    manipulate:
      - title:
          replace:
            regexp: MP4
            format: 720p
      - title:
          replace:
            regexp: \)\.\s\(
            format: ') [webdl 480p]. ('
      - title:
          replace:
            regexp: '[0-9]\.\s\('
            format: ') [webdl 480p]. ('
      - title:
          replace:
            regexp: '[^\]]\.\s\(S'
            format: '. [webdl 480p]. (S'
    urlrewrite:
      lostfilm:
        regexp: 'http://lostfilm.tv/download.php\?(?P<details>.*)'
        format: 'http://www.lostfilm.tv/download.php?\g<details>'
    include: lostfilm.yml
  Newstudio:
    template:
      - tvshows
    manipulate:
      - url:
          replace:
            regexp: '&amp;'
            format: '&'
      - title:
          replace:
            regexp: 'Сезон\s(\d+),\sСерия\s(\d+)'
            format: s\1e\2
      - title:
          replace:
            regexp: Rip
            format: ' 480p'
      - url:
          replace:
            regexp: 'newstud\.io'
            format: 'newstudio.tv'
    rss:
      url: http://localhost:5050/http%3A%2F%2Fnewstudio.tv%2Frss.php%3Fuser%3Dasm0dey%26pass%3D***REMOVED***
    include: newstudio.yml
  #Alexfilm:
    #template:
      #- mailpack
    #manipulate:
      #- title:
          #replace:
            #regexp: WEB-DLRip
            #format: 'webdl 480p'
    #set:
      #path: '/media/sda3/Video/Series/{{series_name}}'
    #disable:
      #- seen
    #rss: http://alexfilm.cc/rss.php?uk=***REMOVED***&uid=19403
    #series:
      #<720p:
        #- 'Old School':
            #alternate_name: 'Старая школа'
        #- 'Serangoon Road':
            #alternate_name: 'Серангун Роуд'
  #To4ka:
    #template:
      #- tvshows
    #headers:
      #COOKIE: uid=4693;pass=***REMOVED***
    #rss: http://to4ka.tv/rss.php?passkey=***REMOVED***
    #manipulate:
      #- title:
          #replace:
            #regexp: WEB-DLRip
            #format: 'webdl 480p'
      #- title:
          #replace:
            #regexp: HDTVRip
            #format: 'webdl 480p'
    #include: to4ka.yml
  tvfedor:
    set:
      path: '/media/sda3/Video/Series/{{series_name}}'
      accept_all: yes
    template:
      - mailpack
    rss: http://litr.cc/rss/download/***REMOVED***
    disable:
      - seen
    rutracker_auth:
      username: 'finkelshteinp'
      password: 'zk.,k.vehxbrf'
    include: tvfedor.yml
  litr-lost:
    template:
      - tvshows
    rss: http://litr.cc/rss/download/***REMOVED***
    include: litr-lost.yml
  litr-baib:
    template:
      - tvshows
    rss: http://litr.cc/rss/download/***REMOVED***
    include: litr-baib.yml
    manipulate:
      - title:
          replace:
            regexp: 'e(\d{2}-)?(\d{2})'
            format: 'e\2'
      - title:
          replace:
            regexp: '/'
            format: ''
      - title:
          replace:
            regexp: '\[Новинка\]\s+'
            format: ''
      - title:
          replace:
            regexp: '\[Закрыта\]\s+'
            format: ''
    set:
      path: '/media/sda3/Video/Series/{{series_name}}'
  #rutracker-films:
    #urlrewrite:
      #rutracker:
        #regexp: '^(?P<id>\d+)$'
        #format: 'http://rutracker.org/forum/viewtopic.php?t=\g<id>'
    #csv:
      #url: file:///home/xbmc/.flexget/rutracker-films.csv
      #values:
        #title: 2
        #url: 1
        #imdb_name: 2
    #thetvdb_lookup: no
    #rutracker_auth:
      #username: 'finkelshteinp'
      #password: 'zk.,k.vehxbrf'
    #imdb_lookup: yes
    #set:
      #path: '/media/sda3/Video/Films/{{title}}'
    #accept_all: yes
    #template:
      #- mailmovie
    #disable:
      #- seen_info_hash

# vim: noai:ts=2:sw=2:et:
