variables: secrets.yml
web_server:
  bind: 0.0.0.0
  port: 3539
  run_v2: true
schedules:
  - tasks: '*'
    interval:
      minutes: 10
templates:
  global:
    make_rss:
      file: /home/xbmc/public_html/flexget.rss
      days: -1
      items: 200
    transmission:
      username: '{? transmission.usr ?}'
      password: '{? transmission.pwd ?}'
    manipulate:
      - url:
          replace:
            regexp: '&amp'
            format: '&'
    metainfo_series: yes
    add_trackers: '{? trackers ?}'
  tvshows:
    thetvdb_lookup: yes
    template:
      - mailshow
    set:
      path: '/media/sda3/Video/Series/{{series_name}}/Season {{series_season}}'
  mailshow:
    notify:
      task:
        template: html.template
        via:
          - email:
              from: ***REMOVED***
              to: '{? email.to ?}'
              smtp_host: smtp.yandex.ru
              smtp_port: 465
              smtp_ssl: true
              smtp_username: '{? email.usr ?}'
              smtp_password: '{? email.pwd ?}'
              smtp_tls: no
              html: yes
  mailpack:
    notify:
      task:
        template: html.template
        via:
          - email:
              from: ***REMOVED***
              to: '{? email.to ?}'
              smtp_host: smtp.yandex.ru
              smtp_port: 465
              smtp_ssl: true
              smtp_username: '{? email.usr ?}'
              smtp_password: '{? email.pwd ?}'
              smtp_tls: no
              #html: yes
  mailmovie:
    notify:
      task:
        template: html.template
        via:
          - email:
              from: ***REMOVED***
              to: '{? email.to ?}'
              smtp_host: smtp.yandex.ru
              smtp_port: 465
              smtp_ssl: true
              smtp_username: '{? email.usr ?}'
              smtp_password: '{? email.pwd ?}'
              smtp_tls: no
              #html: yes
tasks:
  Newstudio:
    template:
      - tvshows
    manipulate:
      - url:
          replace:
            regexp: '&amp;'
            format: '&'
      - title:
          replace:
            regexp: 'Сезон\s(\d+),\sСерия\s(\d+)'
            format: s\1e\2
      - title:
          replace:
            regexp: Rip
            format: ' 480p'
      - url:
          replace:
            regexp: 'newstud\.io'
            format: 'newstudio.tv'
    rss:
      url: '{? newstudio.address ?}'
      escape: yes
    include: newstudio.yml
  litr-lostfilm:
    template:
      - tvshows
    rss: '{? litr.address ?}'
    include: litr-lost.yml
  litr-baibako:
    template:
      - tvshows
    rss: '{? litr.address ?}'
    include: litr-baib.yml
    manipulate:
      - title:
          replace:
            regexp: 'e(\d{2}-)?(\d{2})'
            format: 'e\2'
      - title:
          replace:
            regexp: '/'
            format: ''
      - title:
          replace:
            regexp: '\[Новинка\]\s+'
            format: ''
      - title:
          replace:
            regexp: '\[Закрыта\]\s+'
            format: ''
    set:
      path: '/media/sda3/Video/Series/{{series_name}}'
  litr-rutr:
    template:
      - tvshows
    rss: '{? litr.address ?}'
    set:
      path: '/media/sda3/Video/Series/{{series_name}}'
    manipulate:
      - title:
          replace:
            regexp: 'Сезон: (\d+) / Серии: 1-(\d+) из \d+'
            format: 's\1e\2'
    series:
      - The Big Bang Theory:
          alternate_name: Теория Большого Взрыва
  rutr-films:
    csv:
      url: file:///home/xbmc/.flexget/films.csv
      values:
        title: 1
        url: 2
    set:
      path: '/media/sda3/Video/Films/{{ title }}'
    accept_all: yes





# vim: noai:ts=2:sw=2:et:
