schedules:
  - tasks: '*'
    interval:
      minutes: 10
templates:
  global:
    make_rss:
      file: /home/xbmc/public_html/flexget.rss
      days: -1
      items: 200
    #deluge: yes
    transmission:
      username: transmission
      password: transmission
    manipulate:
      - url:
          replace:
            regexp: '&amp'
            format: '&'
    thetvdb_lookup: yes
    metainfo_series: yes
  tvshows:
    template:
      - mailshow
    set:
      path: '/media/sda3/Video/Series/{{series_name}}/Season {{series_season}}'
    content_size: {max: 4300}
  mailshow:
    email:
      from: ***REMOVED***
      to:
        #- mail@example.com
        - ***REMOVED***
        - ***REMOVED***
      subject: "Недавно скачанные сериалы"
      template: html-dark
      smtp_host: smtp.yandex.ru
      smtp_port: 465
      smtp_ssl: true
      smtp_login: true
      smtp_username: "***REMOVED***"
      smtp_password: "***REMOVED***"
       #smtp_ssl: yes
      smtp_tls: true
  mailpack:
    email:
      from: ***REMOVED***
      to:
        - ***REMOVED***
        - ***REMOVED***
      subject: "Недавно скачанные сериалы"
      template: html
      smtp_host: smtp.yandex.ru
      smtp_port: 465
      smtp_ssl: true
      smtp_login: true
      smtp_username: "***REMOVED***"
      smtp_password: "***REMOVED***"
      # smtp_ssl: yes
      smtp_tls: true
  mailmovie:
    email:
      from: ***REMOVED***
      to:
        - ***REMOVED***
        - ***REMOVED***
      subject: "Недавно скачанные фильмы"
      template: html
      smtp_host: smtp.yandex.ru
      smtp_port: 465
      smtp_ssl: true
      smtp_login: true
      smtp_username: "***REMOVED***"
      smtp_password: "***REMOVED***"
      # smtp_ssl: yes
      smtp_tls: true
tasks:
  Baibako:
    #manipulate:
      #- title:
          #replace:
            #format: h264
            #regexp: x264
    #rss: http://baibako.tv/rss2.php?feed=dl&passkey=***REMOVED***&cat=352
    rss: http://baibako.tv/rss2.php?feed=dl&passkey=***REMOVED***
    template:
      - tvshows
    include: baibako.yml
  Lostfilm:
    verify_ssl_certificates: no
    #proxy: http://46.28.202.209 :8080
    template:
      - tvshows
    headers:
      cookie: uid=902055; pass=***REMOVED***; usess=***REMOVED***;
    rss: http://www.lostfilm.tv/rssdd.xml
    manipulate:
      - title:
          replace:
            regexp: MP4
            format: 720p
      - title:
          replace:
            regexp: \)\.\s\(
            format: ') [webdl 480p]. ('
      - title:
          replace:
            regexp: '[0-9]\.\s\('
            format: ') [webdl 480p]. ('
      - title:
          replace:
            regexp: '[^\]]\.\s\(S'
            format: '. [webdl 480p]. (S'
    urlrewrite:
      lostfilm:
        regexp: 'http://lostfilm.tv/download.php\?(?P<details>.*)'
        format: 'http://www.lostfilm.tv/download.php?\g<details>'
    include: lostfilm.yml
  Newstudio:
    template:
      - tvshows
    manipulate:
      - title:
          replace:
            regexp: 'Сезон\s(\d+),\sСерия\s(\d+)'
            format: s\1e\2
      - title:
          replace:
            regexp: Rip
            format: ' 480p'
      - url:
          replace:
            regexp: 'newstud\.io'
            format: 'newstudio.tv'
    rss: http://newstudio.tv/rss.php?user=asm0dey&pass=***REMOVED***
    include: newstudio.yml
  Alexfilm:
    template:
      - mailpack
    manipulate:
      - title:
          replace:
            regexp: WEB-DLRip
            format: 'webdl 480p'
    set:
      path: '/media/sda3/Video/Series/{{series_name}}'
    disable:
      - seen
    rss: http://alexfilm.cc/rss.php?uk=***REMOVED***&uid=19403
    series:
      <720p:
        - 'Old School':
            alternate_name: 'Старая школа'
        - 'Serangoon Road':
            alternate_name: 'Серангун Роуд'
  To4ka:
    template:
      - tvshows
    headers:
      COOKIE: uid=4693;pass=***REMOVED***
    rss: http://to4ka.tv/rss.php?passkey=***REMOVED***
    manipulate:
      - title:
          replace:
            regexp: WEB-DLRip
            format: 'webdl 480p'
      - title:
          replace:
            regexp: HDTVRip
            format: 'webdl 480p'
    include: to4ka.yml
  tvfedor:
    set:
      path: '/media/sda3/Video/Series/{{series_name}}'
      accept_all: yes
    template:
      - mailpack
    rss: http://litr.cc/rss/download/***REMOVED***
    disable:
      - seen
    rutracker_auth:
      username: 'finkelshteinp'
      password: 'zk.,k.vehxbrf'
    urlrewrite:
      rutor:
        regexp: 'http://zerkalo-rutor.org/torrent/(?P<id>)' 
        format: 'http://zerkalo-rutor.org/download/\g<id>'
      rutor:
        regexp: 'http://rutor.org/torrent/(?P<id>)' 
        format: 'http://d.rutor.org/download/\g<id>'
    include: tvfedor.yml
  rutracker-films:
    urlrewrite:
      rutracker:
        regexp: '^(?P<id>\d+)$'
        format: 'http://rutracker.org/forum/viewtopic.php?t=\g<id>'
    csv:
      url: file:///home/xbmc/.flexget/rutracker-films.csv
      values:
        title: 2
        url: 1
        imdb_name: 2
    thetvdb_lookup: no
    rutracker_auth:
      username: 'finkelshteinp'
      password: 'zk.,k.vehxbrf'
    imdb_lookup: yes
    set:
      path: '/media/sda3/Video/Films/{{title}}'
    accept_all: yes
    template:
      - mailmovie
    disable:
      - seen_info_hash
